name: bert-cn
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.10.12
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - faiss-cpu
  - pip
  - pip:
    - transformers==4.31.0
    - datasets
    - evaluate
    - seqeval
    - accelerate>=0.20.1
    - nltk
    - rouge_chinese
