spring:
  application:
    name: fs-lm-service
  profiles:
    active: dev,idev
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: com.iisquare.fs.web.lm.dsconfig.NamingStrategy
