fs:
  rpc:
    secret: fs-project
  format:
    date: yyyy-MM-dd HH:mm:ss
  site:
    urls:
      file: //127.0.0.1:7812
      static: //127.0.0.1/fs-project-vip/static/resources
  app:
    file:
      dir: web/file/uploads
      secret: fs-project

rpc:
  member:
    name: fs-member-service
    rest: http://127.0.0.1:7801
  xlab:
    name: fs-xlab-service
    rest: http://127.0.0.1:7805
  spider:
    name: fs-spider-service
    rest: http://127.0.0.1:7806
  admin:
    name: fs-admin-service
    rest: http://127.0.0.1:7808
  face:
    name: fs-face-service
    rest: http://127.0.0.1:7809
  lucene:
    name: fs-lucene-service
    rest: http://127.0.0.1:7810
  file:
    name: fs-file-service
    rest: http://127.0.0.1:7812
  worker:
    name: fs-worker-service
    rest: http://127.0.0.1:7813
  bi:
    name: fs-bi-service
    rest: http://127.0.0.1:7815
  oa:
    name: fs-oa-service
    rest: http://127.0.0.1:7816
  cms:
    name: fs-cms-service
    rest: http://127.0.0.1:7817
  shop:
    name: fs-shop-service
    rest: http://127.0.0.1:7818
  cron:
    name: fs-cron-service
    rest: http://127.0.0.1:7819
  govern:
    name: fs-govern-service
    rest: http://127.0.0.1:7820
  auto:
    name: fs-auto-service
    rest: http://127.0.0.1:7821
  spark:
    name: fs-spark-service
    rest: http://127.0.0.1:7822
  flink:
    name: fs-flink-service
    rest: http://127.0.0.1:7823

feign:
  hystrix:
    enabled: true # Enable Fallback
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 15000
      fs-dag-service:
        connectTimeout: 1000
        readTimeout: 60000
      fs-xlab-service:
        connectTimeout: 1000
        readTimeout: 60000
      fs-face-service:
        connectTimeout: 1000
        readTimeout: 60000
      fs-lucene-service:
        connectTimeout: 1000
        readTimeout: 60000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 5000

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  servlet:
    encoding:
      charset: UTF-8

spring:
  servlet:
    multipart:
      maxFileSize: 128MB
      maxRequestSize: 128MB
  thymeleaf:
    mode: HTML
    suffix: .html
    cache: false
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 500
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin888
    virtual-host: /fs-project
    listener:
      simple:
        acknowledge-mode: manual
        default-requeue-rejected: false
  mongodb:
    # https://www.mongodb.com/docs/drivers/java/sync/v4.5/fundamentals/connection/connection-options/
    uri: mongodb://root:admin888@127.0.0.1:27017/
  elasticsearch:
    nodes: 127.0.0.1:9200
  neo4j:
    uri: neo4j://127.0.0.1:7687
    username: neo4j
    password: admin888

  datasource:
    primary:
      table-prefix: fs_demo_
      url: jdbc:mysql://127.0.0.1:3306/fs_project?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      jdbc-url: jdbc:mysql://127.0.0.1:3306/fs_project?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: admin888
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
    member:
      table-prefix: fs_member_
      url: jdbc:mysql://127.0.0.1:3306/fs_project?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      jdbc-url: jdbc:mysql://127.0.0.1:3306/fs_project?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: admin888
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
    spider:
      table-prefix: fs_spider_
      url: jdbc:mysql://127.0.0.1:3306/fs_project?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      jdbc-url: jdbc:mysql://127.0.0.1:3306/fs_project?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: admin888
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
    face:
      table-prefix: fs_face_
      url: jdbc:mysql://127.0.0.1:3306/fs_project?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      jdbc-url: jdbc:mysql://127.0.0.1:3306/fs_project?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: admin888
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
    lucene:
      table-prefix: fs_lucene_
      url: jdbc:mysql://127.0.0.1:3306/fs_project?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      jdbc-url: jdbc:mysql://127.0.0.1:3306/fs_project?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: admin888
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
    file:
      table-prefix: fs_file_
      url: jdbc:mysql://127.0.0.1:3306/fs_project?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      jdbc-url: jdbc:mysql://127.0.0.1:3306/fs_project?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: admin888
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
    bi:
      table-prefix: fs_bi_
      url: jdbc:mysql://127.0.0.1:3306/fs_project?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      jdbc-url: jdbc:mysql://127.0.0.1:3306/fs_project?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: admin888
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
    oa:
      table-prefix: fs_oa_
      url: jdbc:mysql://127.0.0.1:3306/fs_project?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      jdbc-url: jdbc:mysql://127.0.0.1:3306/fs_project?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: admin888
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
    cms:
      table-prefix: fs_cms_
      url: jdbc:mysql://127.0.0.1:3306/fs_project?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      jdbc-url: jdbc:mysql://127.0.0.1:3306/fs_project?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: admin888
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
    shop:
      table-prefix: fs_shop_
      url: jdbc:mysql://127.0.0.1:3306/fs_project?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      jdbc-url: jdbc:mysql://127.0.0.1:3306/fs_project?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: admin888
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
    workflow:
      url: jdbc:mysql://127.0.0.1:3306/fs_workflow?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      jdbc-url: jdbc:mysql://127.0.0.1:3306/fs_workflow?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: admin888
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
    cron:
      table-prefix: fs_cron_
      url: jdbc:mysql://127.0.0.1:3306/fs_quartz?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      jdbc-url: jdbc:mysql://127.0.0.1:3306/fs_quartz?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: admin888
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
    govern:
      table-prefix: fs_govern_
      url: jdbc:mysql://127.0.0.1:3306/fs_project?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      jdbc-url: jdbc:mysql://127.0.0.1:3306/fs_project?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: admin888
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
    auto:
      table-prefix: fs_auto_
      url: jdbc:mysql://127.0.0.1:3306/fs_project?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      jdbc-url: jdbc:mysql://127.0.0.1:3306/fs_project?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: admin888
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
