name: llama2-cn
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.10.12
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - scipy
  - pip
  - pip:
    - transformers==4.31.0
    - accelerate==0.21.0
    - bitsandbytes==0.39.0
