spring:
  application:
    name: fs-face-service
  profiles:
    active: dev,idev
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: com.iisquare.fs.web.face.dsconfig.NamingStrategy
